% =========================================================================
% Practical 2: Mandelbrot-Set Serial vs Parallel Analysis
% =========================================================================
%
% GROUP NUMBER:
%
% MEMBERS:
%   - Member 1 Name, Student Number
%   - Member 2 Name, Student Number

%% ========================================================================
%  PART 1: Mandelbrot Set Image Plotting and Saving
%  ========================================================================
%
% TODO: Implement Mandelbrot set plotting and saving function


%Should take input data from both computations and output function
%input data being resolution , iteration counts (image_data)
%the idea is once the image data is calcuulated in the computation
%function(s) it can just be plugged into plot to well plot!
function mandelbrot_plot(img_data, width, height, method_type) 

    figure;

    imagesc(img_data); %imagsc creates a colour map/image based on the values given in a matrix, with colours being decided are 
                      %similar to that of a heat map where higher number =
    colormap(hot);                 %warmer colour (i think)
    colorbar;

    title(sprintf('Mandelbrot Set  %d x %d', width, height),'FontSize', 12);

%saving file
 filename = ['mandelbrot_', method_type, '_', num2str(width), 'x', num2str(height), '.png'];
   saveas(gcf, filename);
    fprintf('Saved: %s\n', filename)
    
end

%% ========================================================================
%  PART 2: Serial Mandelbrot Set Computation
%  ========================================================================`
%
%TODO: Implement serial Mandelbrot set computation function
function mandelbrot_serial(varargin) %Add necessary input arguments 
    
end

%% ========================================================================
%  PART 3: Parallel Mandelbrot Set Computation
%  ========================================================================
%
%TODO: Implement parallel Mandelbrot set computation function
function mandelbrot_parallel(varargin) %Add necessary input arguments 
    
end

%% ========================================================================
%  PART 4: Testing and Analysis
%  ========================================================================
% Compare the performance of serial Mandelbrot set computation
% with parallel Mandelbrot set computation.

function run_analysis_mandle()
    %Array conatining all the image sizes to be tested
    image_sizes = [
        [800,600],   %SVGA
        [1280,720],  %HD
        [1920,1080], %Full HD
        [2048,1080], %2K Cinema
        [2560,1440], %2K QHD
        [3840,2160], %4K UHD
        [5120,2880], %5K
        [7680,4320]  %8K UHD
    ]

    max_iterations = 1000; 
    
    %TODO: For each image size, perform the following:
    %   a. Measure execution time of mandelbrot_serial
    %   b. Measure execution time of mandelbrot_parallel
    %   c. Store results (image size, time_serial, time_parallel, speedup)  
    %   d. Plot and save the Mandelbrot set images generated by both methods
    
end

N = 5;
M = 10;
C = zeros(M,N);

tic
parfor i = 1:M
    for j = 1:N
        C(i, j) = i*j;
        
    end
end
toc
